version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: repo_plaza_development
      POSTGRES_USER: repo_plaza
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: